### ISSUE TITLE
Edit `sort` schema on admin settings

### ISSUE THREAD

**Issue by leomp12** [ecomclub/app-melhor-envio#21]
Why are you using `sort.by` instead of `sort` only?

https://github.com/ecomclub/app-melhor-envio/blob/eeeece2de1ae0712747b1e72330728f64a13059e/assets/app.json#L55

The `sort` is defined as an object with just one property (`by`), imp the `sort` property may be the enum itself, and so the schema would be simpler.
In addition, the enum options should be more descriptive, eg.: "Preço crescente"

**Comment by talissonf** [comment]
I do not really remember why I include this 'by' in the sort object. I'm going to change it, I'll also check if I did the same redundancy in the wirecard schema.
