### ISSUE TITLE
descrições melhor envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#29]
![Captura de tela de 2019-12-17 12-24-27](https://user-images.githubusercontent.com/35343551/71009141-854a2b80-20c8-11ea-9c17-f0b93af1a6e3.png)
Daria para resumir essas descrições de aviso de recebimento e demais?
Pois ficou muito grande no market. Se quiser posso até te passar o que deixar escrito

**Comment by talissonf** [comment]
Pode sim matheus, me envia o resumo.

**Comment by matheusgnreis** [comment]
Enviei no slack
