### ISSUE TITLE
Erro na loja - Store id 1035 

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#32]
As formas de envio renderizam na loja, mas ao finalizar o pagamento, o erro é:

/@checkout.json{"status":400,"error_code":"CKT901","message":"Any valid shipping service from /calculate_shipping module","user_message":{"en_us":"Shipping method not available, please choose another","pt_br":"Forma de envio indisponível, por favor escolha outra"},"more_info":null}

Já escolhi todas as 4 que aparecem e nenhuma mostra.

**Comment by talissonf** [comment]
Qual é a url da loja?

**Comment by matheusgnreis** [comment]
kelvys-camisetas.netlify.com/

**Comment by talissonf** [comment]
@matheusgnreis não me parece ser um erro do app, acho que pode ser o storefront, pois o módulo ta respondendo com o calculo do frete, além do mais as opções de shipping estão sendo enviadas para o modulo checkout conforme o que foi selecionado.
@leomp12 pode verificar isso?

**Comment by leomp12** [comment]
@matheusgnreis consegue o body da requisição no checkout?

**Comment by matheusgnreis** [comment]
Sim, vou te mandar no slack porque tem dado sensível

**Comment by leomp12** [comment]
Não acho que seja o Storefront, talvez a API de módulos, mas não tenho certeza também.
Parece que o app não está retornando erro, então não vai ter registro em log, talvez só esteja retornando sem os serviços de entrega ou talvez os código de serviço não estejam batendo no checkout.
Acho que o jeito mais fácil de descartar o erro do app é instalar o app dos Correios direto (ou algum outro de entrega) e testar o checkout com ele.

**Comment by matheusgnreis** [comment]
Cheguei a instalar o app dos correios na loja, usando sem contrato e deu erro 500, depois desinstalei, mas se quiser posso fazer novamente e te enviar o body dele também

**Comment by leomp12** [comment]
Deixa o do Correios e faz mais um teste então por favor, se ele retornou erro eu consigo ver os logs aqui.

**Comment by leomp12** [comment]
```console
ecomplus-secondary [Thu Mar 26 2020 16:03:41 GMT-0300 (-03)]
{
  "error": "CALCULATE_ERR",
  "message": "Zip code is unset on app hidden data (merchant must configure $
}
  ---  //  ---
```

Do Correios foi isto aí que deu o 500, configurou o CEP dele certin?

**Comment by matheusgnreis** [comment]
Bom Talisson, fiz teste alguns testes nos correios e passou dos correios, só não passou do PayPal Plus, porque o cartão era inválido. E ai dá a resposta:

```{"status":409,"error_code":"CKT704","message":"No valid transaction object from /create_transaction","user_message":{"en_us":"Your order was saved, but we were unable to make the payment, please contact us","pt_br":"Seu pedido foi salvo, mas não conseguimos efetuar o pagamento, por favor entre em contato"},"more_info":null}```

Que é devido a forma de pagamento, mas o Melhor Envio sempre dá a resposta:

```@checkout.json{"status":400,"error_code":"CKT901","message":"Any valid shipping service from /calculate_shipping module","user_message":{"en_us":"Shipping method not available, please choose another","pt_br":"Forma de envio indisponível, por favor escolha outra"},"more_info":null}```

Ou seja, parece que os correios parece que está passando do envio e partindo para o pagamento, enquanto Melhor envio não

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-melhor-envio/commit/7ef015b27f4b6c4255c93fd7d75a604f15a2460b
