### ISSUE TITLE
Permitir o lojista desabilitar via aplicativo determinado serviço

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#33]
Boa tarde Talisson, creio que você fez algo parecido no Pagseguro, se não me engano (No app, permitiu desabilitar formas de pagamento que não iria utilizar). No caso, permitir o cliente desabilitar as formas de envio que não vá utilizar.

**Comment by talissonf** [comment]
Matheus essa opção ta funcionando diretamente no painel do aplicativo já! O lojista precisa definir uma faixa de cep e informar o nome do serviço a ser desativado.
