### ISSUE TITLE
Habilitar por padrão todas formas de envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#34]
Conforme o issue anterior, se for habilitar todos, talvez buscar todos mesmo, porque eles tem por exemplo Azul Cargo, Latam Cargo, Via Brasil, no momento ele pega apenas jadlog e correios. No caso, eu acho que ou você pega apenas o que o lojista solicitar, ou você pega todos e deixa ele desabilitar aquele que preferir não usar

**Comment by talissonf** [comment]
@matheusgnreis por padrão eu retorno no calculate shipping todos os serviços que o melhor envio me retorno para aquele usuário. Eu só desabilito os serviços caso o lojista configure no painel.
