### ISSUE TITLE
Label do serviço.

### ISSUE THREAD

**Issue by vitorrgg** [ecomclub/app-melhor-envio#35]
É ideal que o label do serviço seja editável no app.

No momento o padrão é o código do serviço, o ideal é que por padrão seja o nome da transportadora pois além de ser mais familiar para os clientes, evita de ser códigos que não fazem sentido.

**Comment by vitorrgg** [comment]
Consegue configurar o app dessa forma @talissonf ?

**Comment by talissonf** [comment]
@vitorrgg @leomp12 como eu ja havia explicado, eu retorno tanto o nome do serviço quanto o nome da transportadora no calculate_shipping, não sei se editar o app seria a melhor forma até porque dependendo do nome que a pessoa configurar pode ficar estranho no widget de calculo de frete se for muito grande, não seria mais facil alterar o que está sendo mostrado no storefront?

**Comment by leomp12** [comment]
@talissonf não porque no Storefront a princípio eu nem sei quais apps ele está usando, eu teria que mockar coisas ou criar uma configuração pra cada app de envio de novo, não faz sentido...
Além disto a propriedade `label` é o _nome da forma de envio mostrada aos clientes_, é diferente da propriedade `service_name`, esta sim é o nome exato do serviço na transportadora e não deve ser customizado pelo lojista.

**Comment by leomp12** [comment]
Outro detalhe é que este label deve se perpetuar além do Storefront, imagine o caso em que um lojista implemente um chatbot por exemplo, ou só tenha mais de um deploy do Storefront...
É uma configuração do app mesmo.

**Comment by leomp12** [comment]
Nos Correios eu uso um array de objetos `services` (https://github.com/ecomplus/app-correios/blob/master/assets/application.json#L57), com `service_code` e `label`, desta forma o lojista pode opcionalmente definir quais serviços vai usar e customizar o label.
Acho que você pode fazer a mesma coisa pro ME.

Obs.: neste caso se o `services` não existir, for um array vazio ou um array com apenas objetos vazios, devemos usar todos os serviços disponíveis por padrão e com os labels padrão (geralmente o nome do serviço mesmo). **`services` não deve ser requerido**

**Comment by talissonf** [comment]
Pronto, precisa atualizar nos apps instalados agora para habilitar a opção de edição das labels

**Comment by leomp12** [comment]
Beleza, falamos com o lojista na comunidade e ele mesmo faz isto quando quiser.
