### ISSUE TITLE
Alguns envios não são enviados na mudança para pronto pra envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#44]
Alguns testes que fiz, apenas na segunda mudança de status que está enviando pedidos. Outros na primeira mudança vai. Mas está recorrente ser somente em mudança posteriores de acordo com a cliente.

**Comment by matheusgnreis** [comment]
Detalhando ainda mais, pedidos feitos pela loja 1125, alterando a primeira vez para **Pronto para envio**, não está indo, somente nas subsequentes.
Temos aqui os pedidos:

- 5f5e48047430f92180eefa55 alterando para pronto para envio, as 18/09/20 14:43:13, no log de error não consta nada e nem o de saída

- 5f5cec4d7430f92180eed53e alterado para pronto para envio, as 10:30 

- 5f5ecfd57430f92180ef15d1

- 5f5e32407430f92180eef724

- 5f5fccac7430f92180ef8061
- 5f5e94bf7430f92180ef0414
- 5f5e84317430f92180ef0201
- 5f5fda287430f92180ef88d6
- 5f5ee46d7430f92180ef1a0b
- 5f5e48047430f92180eefa55
- 5f56f9117430f92180ecabbd
- 5f5f88e17430f92180ef5002
-5f5e9f587430f92180ef0860

**Comment by leomp12** [comment]
@talissonf só pra te dar uma feedback disso aqui, seu procedure não deveria ser com o field `fulfillments` porque você checa o status no `fulfillment_status` (que é o correto mesmo), não no `fulfillments`, os campos não necessariamente estarão sincronizados, muitas vezes o campo de status é atualizado depois, mas aí você já pode ter recebido o webhook antes e no momento que recebeu o `fulfillment_status` não bateu sua condição.

Outras vezes o `fulfillments` pode nem ser preenchido, pode haver só um set direto no `fulfillment_status` e isto já deveria ser suficiente para receber a notificação e iniciar as etiquetas. O equivalente acontece com `payments_history` e `financial_status`, em geral os procedures devem ser baseados no status, não no histórico.

Além disto o procedure não deveria ser só no `change` porque é possível que o pedido já entrasse em alguma ocasião como preparado para envio, não há nada de errado com isto e neste caso já deveria ir pro ME.

**Comment by leomp12** [comment]
@matheusgnreis quando puder testar por favor, dando certo fecha o issue pra nós...

> A partir deste release também vai retornar a mensagem de erro do ME no cálculo, e só vái pro log erros que não são de configuração do lojista no ME. Quando há erro pra comprar etiqueta a mensagem é salva no `hidden_metafields` do pedido (isso já era feito), tem que checar lá primeiro porque erros de CPF e saldo também não vão pro log mais pra evitar flodar (e vermos quando houver um erro do app propriamente).

**Comment by leomp12** [comment]
@matheusgnreis esqueci de falar, como mudei os triggers tem que reinstalar o app pra criar o procedure certo (ou fazer via API).
