### ISSUE TITLE
Trazer código de rastreio do Melhor Envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#45]
Quando há a compra ou a mudança para enviado, é necessário que o código de rastreio ou o link de rastreio (melhor ainda) venha antes do pedido ser modificado para enviado. Pois se não, o email é disparado antes do código de rastreio entrar na loja e vai sem ele. No momento, de acordo com a lojista, ela está tendo que inserir manualmente um por um, pois o status apenas muda para enviado e não vem essa informação no pedido. Como são muitos pedidos por dia, ela está tendo um trabalho demasiado em enviar cliente por cliente.

Um exemplo do link de rastreio é https://www.melhorrastreio.com.br/rastreio/PZ121491078BR, então dá pra fixar o link e colocar só o código posterior por exemplo, não sei se o melhor envio já fornece isso diretamente por ser uma ferramenta deles.

**Comment by leomp12** [comment]
@matheusgnreis não tenho certeza porque a documentação da API do Melhor Envio não tem exemplos de respostas, então ainda não sei se eles retornam o código de rastreio no checkout mesmo :neutral_face: 
Mas eu acho que sim, se não vai debugar a resposta no próximo checkout também.

**Comment by leomp12** [comment]
Fixei o código e link que estava sendo salvo (às vezes) com o job para tracking também.

**Comment by leomp12** [comment]
Não dá pra pegar o código logo após a compra da etiqueta porque ele vem `null`, mas certifiquei de que ele é salvo no pedido antes da atualização de status.

**Comment by matheusgnreis** [comment]
Beleza, valeu!
