### ISSUE TITLE
Envio não comercial não funciona

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#46]
No caso de transportadoras, se não tiver NF no pedido deveria ser enviado com o atributo não comercial, atualmente o pedido não é enviado. Segue uma nota da documentação:

**Nota: para transportadoras privadas (todas menos Correios), o campo options.invoice.key é obrigatório e deve conter a chave da NF. Isto pode ser contornado configurando o envio para que o mesmo seja um envio não comercial (com declaração de conteúdo), para isto deve ser setada a flag options.non_commercial como true.**

Loja em que está ocorrendo os erros:
ID 1073 e pedidos número: 6411 e 6413

**Comment by matheusgnreis** [comment]
@talissonf

**Comment by talissonf** [comment]
@matheusgnreis vou ver o que ta rolando.

**Comment by talissonf** [comment]
@matheusgnreis a opção de envio não comercial estava funcionando.
Eu acredito que o que estava acontecendo era que quando o pedido tinha seu status alterado o app verificava o fulfillment_status e la permanecia o mesmo status e por isso o app ignorava a compra da etiqueta, já que o fulfillment_status leva um tempo pra atualizar o seu valor junto as entradas no fulfillments. 
Eu alterei isso e agora o app verifica as entradas no fulfillments verificando se a ultima é ready_for_shipping. Acredito que com esse  fix(https://github.com/ecomplus/app-melhor-envio/commit/924485a2d57ef4024a83613411c960ef2c400931) isso deve ser resolvido!

**Comment by matheusgnreis** [comment]
OK, vou informar para testar
