### ISSUE TITLE
Webhooks ignorados para geração de etiquetas no ME

### ISSUE THREAD

**Issue by leomp12** [ecomclub/app-melhor-envio#47]
Quando o lojista altera o status duas vezes em sequência (muito próximo) pode acontecer de o primeiro status ficar salvo por último no histórico, ainda assim o `fulfillment_status` fica correto e por isso espera-se que a etiqueta seja gerada.

Como o trigger do procedure é filtrado pelo [field `fulfillment_status`](https://github.com/ecomplus/app-melhor-envio/blob/master/lib/store-api/procedures.js#L24), de qualquer forma é mais lógico que o `fulfillment_status.current` (mais consistente) seja checado neste caso e não o `fulfillments`, já que o app será notificado exclusivamente quando o `fulfillment_status` for alterado, independente do histórico ser preenchido antes ou depois.

> Em outros casos, em handlers com mais criticidade de tempo de resposta, o trigger estaria no `fulfillments` e aí sim deveria ser checado o último status no histórico.

**Comment by leomp12** [comment]
Isso tem acontecido com frequência porque alteram para _Em produção_ e logo depois _Pronto para envio_, isto não está correto mas de qualquer forma é melhor evitarmos "erros" e demanda de suporte.

**Comment by leomp12** [comment]
@matheusgnreis @ThaisChaves quando este issue for fechado o app do Melhor Envio pode voltar a não gerar as etiquetas _sempre_ em instalações mais antigas, se alguém reclamar é necessário primeiro verificar a versão instalada :+1:

**Comment by leomp12** [comment]
@talissonf na verdade mesmo em casos em que o histórico fica correto a etiqueta pode não ser gerada porque no painel a alteração no form de pedido envia um PATCH em `/orders/_id.json`, alterando diretamente o `fulfillment_status`, em seguida o CPM adiciona a entrada no histório mas isso é assíncrono e portanto, com o procedure como está e o tratamento do webhook como está, é possível que o evento seja ignorado.

Na prática é só manter sempre a checagem no mesmo field que é critério do trigger, neste caso o `fulfillment_status`.

**Comment by talissonf** [comment]
https://github.com/ecomplus/app-melhor-envio/commit/28ab817ed6b411b8fd047d570dce6e12896ea016
