### ISSUE TITLE
Erro de Pedido não enviado ao melhor envio

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#51]
Pedido
https://app.e-com.plus/#/resources/orders/6043b4286d50911b60560894
Erro:
“value”: “{“error”:“O Código de unidade informado não pertence à transportadora do serviço escolhido”}
Não sei se tem algo haver, mas colocando o código jadlog, ele vai em todas as formas de envio. Esse foi apenas 1 que deu problema, teve um outro que deu também e era correios.

**Comment by matheusgnreis** [comment]
Coisasdateca também começou a dar esse erro no log. Ela não sabe ainda, mas tem vários pedidos com esse erro

**Comment by talissonf** [comment]
Não seria interessante olhar com o suporte do melhor envio? se não tiver tido alteração no app é bom saber se eles mudaram algo

**Comment by matheusgnreis** [comment]
Já entrei em contato lá pra saber, pediram alguns dados e respondi. Esperando o retorno deles.
