### ISSUE TITLE
Duas lojas reclamaram que o rastreio não está funcionando

### ISSUE THREAD

**Issue by matheusgnreis** [ecomclub/app-melhor-envio#53]
Uma delas de store id 1095 tem o pedido 60820fac3983002ac495dabd, vi no log que foi salvo direitinho no banco de dados, mas na loja não alterou nada. Na loja 1035 por exemplo, o pedido 607dea9f71f42b0eaf7767b3, foi modificado manualmente, pelo que vi tem vários de março que não alteração nem em abril

**Comment by talissonf** [comment]
Uai, vou ver

**Comment by leomp12** [comment]
@talissonf não tinha visto que c ia mexer, era só a fila travada com labels velhos demais e às vezes dando fatal `getConfig` sem catch, no Frenet era a mesma coisa:

closes with https://github.com/ecomplus/app-melhor-envio/commit/1cc85027ba9a47b738ff5f59d083e5e200b47486

**Comment by leomp12** [comment]
@talissonf mas se tiver boiando aí e quiser ver mesmo nos dá uma mão nisso aqui https://github.com/ecomplus/app-mailchimp/issues , sei nem por onde começar nesse aí 😁

**Comment by talissonf** [comment]
@leomp12 foi mal tmb nao vi sua resposta :$, mas vou dar uma olhada nesses issues hoje mais tarde e te dou um retorno. Tem tanto tempo que não mexo com isso tmb que nem eu sei mais por onde começar.
